CREATE TABLE Articles
(
id BIGINT NOT NULL,
guid VARCHAR(255) NOT NULL,
title VARCHAR(255),
link VARCHAR(255),
originalPubDate TIMESTAMP,
description VARCHAR(500),
content VARCHAR(10000),
thumbnail VARCHAR(255),
PRIMARY KEY (id)
)

CREATE TABLE Birthdays
(
id BIGINT NOT NULL AUTO_INCREMENT,
lastPosted BIGINT NOT NULL,
person VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
)

CREATE TABLE Fixtures
(
id BIGINT NOT NULL AUTO_INCREMENT,
awayTeam VARCHAR(50) NOT NULL,
homeTeam VARCHAR(50) NOT NULL,
date TIMESTAMP NOT NULL,
competition VARCHAR(50) NOT NULL,
season INT NOT NULL,
PRIMARY KEY (id)
)

CREATE TABLE `Instagram` (
  `href` varchar(255) NOT NULL,
  PRIMARY KEY (`href`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Players
(
id BIGINT NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
dateOfBirth TIMESTAMP NOT NULL,
position VARCHAR(50) NOT NULL,
dateJoined TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
previousClubs VARCHAR(250),
squadNumber INT,
PRIMARY KEY (id)
)

CREATE TABLE Twits
(
id BIGINT NOT NULL AUTO_INCREMENT,
href VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
)

CREATE TABLE `Youtube` (
  `href` varchar(255) NOT NULL,
  PRIMARY KEY (`href`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;